version: "3"

services:
  react-app:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
    tty: true
    depends_on:
      - api-server
  api-server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    container_name: express-container
    volumes:
      - ./server:/app
volumes:
  projectData:
